name: pixabay_image_setu
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # networking libraries
  flutter_bloc: ^8.1.2
  dio: ^5.0.3
  retrofit: ^4.0.1
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.9

  freezed: ^2.3.2
  logger: ^1.3.0
  pretty_dio_logger: ^1.3.1
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  #  utils
  connectivity: ^3.0.6
  google_fonts: ^6.1.0
  flutter_smart_dialog:
  shimmer: ^3.0.0
  intl: ^0.18.1
  fluttertoast: ^8.2.4
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - .env

